name: gaia # you probably want to 'snapcraft register <name>'
# base: core18 # the base snap is the execution environment for this snap
version: '0.28.0~rc2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Gaia Daemon # 79 char long summary
description: |
  This snap provides the Gaia daemon gaiad and the command line
  tool gaiacli.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    gaiad:
        command: bin/gaiad
        plugs: [home]
    gaiacli:
        command: bin/gaiacli
        plugs: [home]

parts:
  gaia:
    plugin: dump
    source: ./
    override-pull: |
        wget https://github.com/cosmos/cosmos-sdk/archive/v0.28.0-rc2.tar.gz
        tar xvf v0.28.0-rc2.tar.gz
        rm v0.28.0-rc2.tar.gz
        mkdir -p go/src/github.com/cosmos bin
        mv cosmos-sdk-0.28.0-rc2/ go/src/github.com/cosmos/cosmos-sdk/
    build-snaps: [go]
    override-build: |
        base=`pwd`
        export GOPATH=`pwd`/go
        echo $GOPATH
        cd go/src/github.com/cosmos/cosmos-sdk
        make get_vendor_deps
        make install
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        cp $GOPATH/bin/gaiad $SNAPCRAFT_PART_INSTALL/bin
        cp $GOPATH/bin/gaiacli $SNAPCRAFT_PART_INSTALL/bin
